import type { Metadata } from "next";
import { generateMetadata, pageMetadata } from "@/lib/seo";

export const metadata: Metadata = generateMetadata(pageMetadata.terms);

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <h1 className="text-4xl font-bold">Terms of Service</h1>
      <p className="text-lg text-gray-600">
        By using Adocavo Intelligence, you agree to the following terms. Please
        read them carefully.
      </p>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Acceptable use</h2>
        <ul className="list-disc pl-5 text-gray-600 space-y-2">
          <li>Use the platform for lawful marketing and creative testing.</li>
          <li>Do not attempt to abuse, scrape, or disrupt the service.</li>
          <li>Respect intellectual property and user privacy.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">AI-generated content</h2>
        <p className="text-gray-600">
          Scripts are generated by AI and should be reviewed before use. You are
          responsible for ensuring compliance with platform policies and local
          laws.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Availability</h2>
        <p className="text-gray-600">
          We aim for high availability, but service interruptions may occur for
          maintenance or updates. We will communicate planned downtime when
          possible.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Contact</h2>
        <p className="text-gray-600">
          For questions about these terms, contact support@adocavo.net.
        </p>
      </section>
    </div>
  );
}
